module.exports = {
	preset: 'ts-jest',
	testEnvironment: 'node',
	roots: ['<rootDir>/src', '<rootDir>/tests'],
	testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
	transform: {
		'^.+\\.ts$': 'ts-jest',
	},
	collectCoverageFrom: [
		'src/**/*.ts',
		'!src/**/*.d.ts',
		'!src/**/*.test.ts',
		'!src/**/*.spec.ts',
		// Exclude CLI entry points and builders
		'!src/cli/index.ts',
		'!src/cli/command-builder.ts',
		'!src/cli/functional.ts',
		'!src/cli/global-options.ts',
		// Exclude CLI commands that require user interaction or are WIP
		'!src/cli/commands/collaborate.ts',
		'!src/cli/commands/create.ts',
		'!src/cli/commands/dashboard.ts',
		'!src/cli/commands/setup.ts',
		'!src/cli/commands/mcp.ts',
		'!src/cli/commands/check.ts',
		'!src/cli/commands/analyze.ts',
		'!src/cli/commands/explain.ts',
		'!src/cli/commands/fix.ts',
		'!src/cli/commands/generate.ts',
		'!src/cli/commands/init.ts',
		'!src/cli/commands/map.ts',
		'!src/cli/commands/migrate.ts',
		'!src/cli/commands/mock.ts',
		'!src/cli/commands/scaffold.ts',
		'!src/cli/commands/sync.ts',
		'!src/cli/commands/watch.ts',
		'!src/cli/commands/diff.ts',
		'!src/cli/commands/docs.ts',
		'!src/cli/commands/stats.ts', // Stats command is a CLI wrapper, core logic tested
		// Exclude experimental/WIP features
		'!src/core/plugin-interactive.ts',
		'!src/core/collaboration/**',
		'!src/core/command-suggestions.ts',
		'!src/core/config.ts',
		'!src/core/error-recovery.ts',
		'!src/core/faker-utils.ts',
		'!src/core/infrastructure.ts',
		'!src/core/memory-optimizer.ts',
		'!src/core/performance-profiler.ts',
		'!src/core/plugin-system.ts',
		'!src/core/progressive-loader.ts',
		'!src/core/schema-diff.ts',
		'!src/core/schema-generation.ts',
		'!src/core/schema-testing.ts',
		'!src/core/schema-transformation.ts',
		'!src/core/testing-infrastructure.ts',
		'!src/core/documentation/**',
		'!src/core/migration/**',
		'!src/index.ts',
		'!src/utils.ts',
		'!src/utils/**',
	],
	coverageDirectory: 'coverage',
	coverageThresholds: {
		global: {
			branches: 35,
			functions: 35,
			lines: 45,
			statements: 45,
		},
		// Individual modules that are well-tested
		'src/core/schema-stats.ts': {
			branches: 65,
			functions: 80,
			lines: 80,
			statements: 75,
		},
		'src/cli/commands/lint.ts': {
			branches: 55,
			functions: 70,
			lines: 60,
			statements: 60,
		},
	},
	setupFilesAfterEnv: ['<rootDir>/tests/simple-setup.ts'],
	testTimeout: 10000,
	verbose: true,
};
